services:
  - type: web
    name: job-search-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api.index:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENABLE_SCHEDULER
        value: "false"            # disable in-process scheduler on Render
      - key: GATE_TZ
        value: "America/Toronto"
      - key: RUN_HOURS_LOCAL
        value: "8,12,17,23"
      # ---- secrets set in dashboard after first deploy ----
      - key: JSEARCH_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAILS
        sync: false

  - type: cron
    name: job-scan-hourly
    env: python
    schedule: "0 * * * *"        # every hour (UTC)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m api.run_scan"
    envVars:
      - key: GATE_TZ
        value: "America/Toronto"
      - key: RUN_HOURS_LOCAL
        value: "8,12,17,23"
      # ---- same secrets for the job ----
      - key: JSEARCH_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
      - key: RECIPIENT_EMAILS
        sync: false
