name: Job Scanner (Test Now)

on:
  workflow_dispatch: {}   # only runs when you click "Run workflow"

jobs:
  scan-now:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      JSEARCH_API_KEY: ${{ secrets.JSEARCH_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
      RECIPIENT_EMAILS: ${{ secrets.RECIPIENT_EMAILS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job scan immediately
        run: python -m api.run_scan
